# Generated by Django 4.2.9 on 2024-02-18 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cp', '0002_alter_user_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cp.car'),
        ),
    ]
