# Generated by Django 4.2.9 on 2024-02-18 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cp', '0004_alter_user_car_name_alter_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cp.car'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
    ]
