# Generated by Django 4.2.9 on 2024-02-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cp', '0005_alter_user_car_name_alter_user_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='car_name',
            new_name='car',
        ),
    ]
